Go/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('admin/', admin.site.urls),
    path('', include('great.urls'))
]

great/urls.py
from django.urls import path

from . import views
app_name = 'great'# для лучшего определения
urlpatterns = [
    # ex: /great/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /great/5
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /great/5/results
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /great/5/vote
    path('<int:question_id>/vote/', views.vote, name='vote'),
]
#<int:question_id>/ выделяет в строке число и обрабатывает его

great/models.py
from django.db import models
from django.utils import timezone
import datetime

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True # выводить визуально на моменте просмотров всех вопросов 
    was_published_recently.short_description = 'Было опубликованно недавно?' # заголовок во время просмотров всех вопросов

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

great/views.py
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .models import Question, Choice

class IndexView(generic.ListView):#generic class заготовок 
    template_name = 'great/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
        pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'great/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'great/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'great/detail.html', {
            'question': question,
            'error_message': "Вы не выбрали ответ.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()

    return HttpResponseRedirect(reverse('great:results', args=(question.id,) ))

great/templates/great/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'great/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'great/detail.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;500;700&display=swap" rel="stylesheet">
    <title>Detail</title>
</head>
<body>
    <header>
        <div><a href="{% url 'great:index' %}">TestApp</a></div>
        <div><a href="/admin">admin</a></div>
    </header>
    <div class="wrapper list">
            <h1>{{ question.question_text }}</h1>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            
            <form action="{% url 'great:vote' question.id %}" method="POST">
                {% csrf_token %}
                {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id}}" />
                <label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label><br />
                {% endfor %}
                <input type="submit" value="Голосовать" class="submit"/>
            </form>
    </div>
</body>
</html>

great/templates/great/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'great/index.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;500;700&display=swap" rel="stylesheet">
    <title>Question</title>
</head>
<body>
    <header>
        <div><a href="/great">TestApp</a></div>
        <div><a href="/admin">admin</a></div>
    </header>
    <div class="wrapper">
        <div class="list">
            {% if latest_question_list %}
                <ul>
                    {% for question in latest_question_list %}
                    <li>
                        <a href="{% url 'great:detail' question.id %}">{{ question.question_text }}</a>
                    </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No great are available.</p>
            {% endif %}
        </div>
    </div>
</body>
</html>

great/templates/great/results.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'great/index.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'great/results.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;300;500;700&display=swap" rel="stylesheet">
    <title>Results</title>
</head>

<body>
    <header>
        <div><a href="{% url 'great:index' %}">TestApp</a></div>
        <div><a href="/admin">admin</a></div>
    </header>
    <div class="wrapper list">
            <h1>{{ question.question_text }}</h1>
            
            <ul>
                {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
                {% endfor %}
            </ul>
            
            <a href="{% url 'great:detail' question.id %}" class="revoteButton">Проголосовать заново</a>
    </div>
</body>

</html>